import { useMemo, useState } from 'react';
import { Link, Navigate, Route, Routes, useLocation, useNavigate, useParams } from 'react-router-dom';
import { Activity, AlertTriangle, ArrowRight, BarChart3, Bell, BookOpen, Box, Check, ChevronRight, Clock3, Cloud, Database, FileCheck2, FolderKanban, Gauge, KeyRound, LayoutDashboard, LifeBuoy, ListChecks, Menu, Network, Plus, RefreshCw, Search, Settings2, Shield, ShieldCheck, SlidersHorizontal, UserRound, Users, X } from 'lucide-react';
import type { LucideIcon } from 'lucide-react';
import { assignments, auditEvents, currentUser, groups, policies, requests, roles, users, type AccessRequest, type Assignment, type RequestStatus, type Role } from './mock';
import { mockService, useMockState } from './mockService';
import { entraConfigured, useAuth } from './auth';
import ProviderConfiguration from './ProviderConfiguration';

const nav = [
  { label: 'Dashboard', icon: LayoutDashboard, to: '/dashboard', roles: ['user','admin'] },
  { label: 'My Access', icon: KeyRound, to: '/my-access', roles: ['user'] },
  { label: 'Request Access', icon: Plus, to: '/request-access', roles: ['user'] },
  { label: 'My Requests', icon: ListChecks, to: '/my-requests', roles: ['user'] },
  { label: 'Profile', icon: UserRound, to: '/profile', roles: ['user'] },
  { label: 'Users', icon: Users, to: '/admin/users', roles: ['admin'], section: 'ADMINISTRATION' },
  { label: 'Groups', icon: Network, to: '/admin/groups', roles: ['admin'] },
  { label: 'Roles', icon: Shield, to: '/admin/roles', roles: ['admin'] },
  { label: 'Access Requests', icon: FolderKanban, to: '/admin/access-requests', roles: ['admin'], section: 'ACCESS MANAGEMENT' },
  { label: 'Assignments', icon: KeyRound, to: '/admin/assignments', roles: ['admin'] },
  { label: 'Policies', icon: SlidersHorizontal, to: '/admin/policies', roles: ['admin'], section: 'GOVERNANCE' },
  { label: 'Audit Logs', icon: BookOpen, to: '/admin/audit', roles: ['admin'] },
  { label: 'Providers', icon: Cloud, to: '/admin/providers', roles: ['admin'], section: 'SYSTEM' },
  { label: 'Sync', icon: RefreshCw, to: '/admin/sync', roles: ['admin'] },
];

function App() {
  const auth = useAuth();
  const [mockRole, setMockRole] = useState<Role>(() => (localStorage.getItem('accesspilot.mockRole') as Role) || 'admin');
  if (entraConfigured && auth.loading) return <div className="empty">Loading AccessPilot authentication...</div>;
  if (entraConfigured && !auth.account) return <div className="empty"><h1>Sign in to AccessPilot</h1><p className="subtitle">Use your Microsoft Entra account to continue.</p><button className="btn btn-primary" onClick={auth.signIn} style={{marginTop:18}}>Sign in</button></div>;
  const role = entraConfigured ? auth.role : mockRole;
  const changeRole = (nextRole: Role) => { localStorage.setItem('accesspilot.mockRole', nextRole); setMockRole(nextRole); };
  return <Shell role={role} setRole={changeRole}><Routes><Route path="/" element={<Navigate to="/dashboard" replace />} /><Route path="/dashboard" element={<Dashboard role={role} />} /><Route path="/my-access" element={<MyAccess />} /><Route path="/request-access" element={<RequestAccess />} /><Route path="/my-requests" element={<Requests mine />} /><Route path="/profile" element={<Profile />} /><Route path="/admin/users" element={<AdminOnly role={role}><UsersPage /></AdminOnly>} /><Route path="/admin/users/:id" element={<AdminOnly role={role}><UserDetail /></AdminOnly>} /><Route path="/admin/groups" element={<AdminOnly role={role}><GroupsPage /></AdminOnly>} /><Route path="/admin/roles" element={<AdminOnly role={role}><RolesPage /></AdminOnly>} /><Route path="/admin/access-requests" element={<AdminOnly role={role}><Requests /></AdminOnly>} /><Route path="/admin/access-requests/:id" element={<AdminOnly role={role}><RequestDetailInteractive /></AdminOnly>} /><Route path="/admin/assignments" element={<AdminOnly role={role}><AssignmentsInteractive /></AdminOnly>} /><Route path="/admin/policies" element={<AdminOnly role={role}><PoliciesPage /></AdminOnly>} /><Route path="/admin/audit" element={<AdminOnly role={role}><AuditPage /></AdminOnly>} /><Route path="/admin/providers" element={<AdminOnly role={role}><ProvidersPage /></AdminOnly>} /><Route path="/admin/sync" element={<AdminOnly role={role}><SyncPage /></AdminOnly>} /><Route path="*" element={<Navigate to="/dashboard" replace />} /></Routes></Shell>;
}
function AdminOnly({ role, children }: { role: Role; children: React.ReactNode }) { return role === 'admin' ? children : <Navigate to="/dashboard" replace />; }
function Shell({ role, setRole, children }: { role: Role; setRole: (r: Role) => void; children: React.ReactNode }) {
  const location = useLocation(); const navigate = useNavigate();
  const auth = useAuth();
  const visible = nav.filter(item => item.roles.includes(role));
  const path = location.pathname;
  return <div className="app"><aside className="sidebar"><Link to="/dashboard" className="brand"><span className="brand-mark">A</span> AccessPilot</Link>{visible.map((item, index) => { const I = item.icon; const previous = visible[index - 1]; return <div key={item.to}>{item.section && item.section !== previous?.section && <div className="nav-label">{item.section}</div>}<Link className={`nav-item ${path === item.to || (item.to !== '/dashboard' && path.startsWith(item.to)) ? 'active' : ''}`} to={item.to}><I />{item.label}</Link></div> })}<div className="sidebar-foot"><div>ACCESSPILOT CONSOLE</div><div style={{marginTop:5}}>v0.1.0 · Mock environment</div></div></aside><main className="main"><header className="topbar"><button className="mobile-menu" aria-label="Open navigation"><Menu size={20}/></button><div className="crumb">Workspace / <strong>{role === 'admin' ? 'Administration' : 'Self-service'}</strong></div><div className="top-actions">{entraConfigured ? <button className="btn" onClick={() => auth.account ? auth.signOut() : auth.signIn()}>{auth.account ? 'Sign out' : 'Sign in'}</button> : <div className="role-switch" aria-label="Development role switcher"><button className={role === 'user' ? 'active' : ''} onClick={() => { setRole('user'); navigate('/dashboard'); }}>User</button><button className={role === 'admin' ? 'active' : ''} onClick={() => { setRole('admin'); navigate('/dashboard'); }}>Admin</button></div>}<Bell size={17} color="#718088"/><div className="profile"><span>{auth.account?.name || currentUser.name}</span><span className="avatar">{currentUser.initials}</span></div></div></header>{children}</main></div>;
}
function Page({ eyebrow, title, subtitle, action, children }: { eyebrow?: string; title: string; subtitle?: string; action?: React.ReactNode; children: React.ReactNode }) { return <div className="content"><div className="page-head"><div>{eyebrow && <div className="eyebrow">{eyebrow}</div>}<h1>{title}</h1>{subtitle && <p className="subtitle">{subtitle}</p>}</div>{action}</div>{children}</div>; }
function StatCards({ admin = false }: { admin?: boolean }) { const stats: Array<[string, string, string, LucideIcon]> = admin ? [['Total users','2,486','+12 this month',Users],['Groups','184','98% synced',Network],['Privileged roles','18','3 under review',ShieldCheck],['Active JIT sessions','27','-8% vs yesterday',Clock3],['Pending requests','14','6 high risk',FolderKanban],['Expiring access','31','Next 24 hours',AlertTriangle],['Provider health','Healthy','Last checked 2m ago',Cloud],['Policy coverage','96.4%','+1.8% this quarter',FileCheck2]] : [['Active access','3','2h 14m remaining',KeyRound],['Eligible access','12','Across 3 providers',Shield],['Pending requests','2','1 needs attention',Clock3],['Expiring soon','1','Within 24 hours',AlertTriangle]]; return <div className={`stats ${admin ? 'admin-stats' : ''}`}>{stats.map(([label,value,foot,I]) => <div className="stat" key={String(label)}><div className="stat-top"><span>{label}</span><span className="stat-icon"><I size={15}/></span></div><div className="stat-value">{value}</div><div className="stat-foot">{foot}</div></div>)}</div>; }
function Dashboard({ role }: { role: Role }) { const admin = role === 'admin'; return <Page eyebrow={admin ? 'ADMINISTRATION' : 'SELF-SERVICE'} title={admin ? 'Good morning, Jordan' : 'Your access overview'} subtitle={admin ? 'Here is what is happening across your identity environment.' : 'Review your current access and request what you need.'} action={<button className="btn btn-primary" onClick={() => {}}><ArrowRight size={15}/> {admin ? 'Review requests' : 'Request access'}</button>}><StatCards admin={admin}/><div className="grid-2"><section className="panel"><div className="panel-head"><h2>{admin ? 'Recent access requests' : 'Recent activity'}</h2><Link to={admin ? '/admin/access-requests' : '/my-requests'} className="panel-link">View all <ChevronRight size={12}/></Link></div>{(admin ? requests : auditEvents.slice(0,5)).map((item, i) => <div className="activity" key={i}><div className="activity-row"><span className="activity-dot"/><div className="activity-copy"><strong>{admin ? (item as AccessRequest).resource : (item as string[])[2]}</strong><small>{admin ? `${(item as AccessRequest).requester} · ${(item as AccessRequest).duration}` : `${(item as string[])[1]} · ${(item as string[])[3]}`}</small></div>{admin ? <StatusBadge status={(item as AccessRequest).status}/> : <span className="time">{(item as string[])[0]}</span>}</div></div>)}</section><section className="panel"><div className="panel-head"><h2>{admin ? 'Provider status' : 'Current active access'}</h2><span className="badge success">All systems healthy</span></div><div className="detail-section"><div className="user-cell"><span className="avatar" style={{background:'#e4f1f5',color:'#33758a'}}><Cloud size={15}/></span><div><div className="user-name">Microsoft Entra ID</div><div className="user-email">Connected · Last sync 2 minutes ago</div></div></div><div className="key-grid" style={{marginTop:24}}><div className="key"><span>Users synced</span><strong>2,486</strong></div><div className="key"><span>Groups synced</span><strong>184</strong></div><div className="key"><span>Directory roles</span><strong>18</strong></div><div className="key"><span>Next sync</span><strong>In 28 minutes</strong></div></div></div>{!admin && <div className="timeline"><div className="timeline-item"><strong>Production Administrator</strong><small>Eligible · Activate up to 4 hours</small></div><div className="timeline-item"><strong>Security Operations</strong><small>Active · Expires today at 18:04</small></div><div className="timeline-item"><strong>Product Analytics</strong><small>Eligible · Activate up to 8 hours</small></div></div>}</section></div></Page>; }
function StatusBadge({ status }: { status: string }) { const cls = ['APPROVED','ACTIVE','COMPLETED','CONNECTED','ELIGIBLE','SUCCESS','Healthy','Active'].includes(status) ? 'success' : ['PENDING','RUNNING','PARTIAL','Medium'].includes(status) ? 'warning' : ['REJECTED','EXPIRED','REVOKED','FAILED','Disabled','High'].includes(status) ? 'danger' : 'neutral'; return <span className={`badge ${cls}`}>{status}</span>; }
function TablePanel({ children, toolbar }: { children: React.ReactNode; toolbar?: React.ReactNode }) { return <><div className="toolbar">{toolbar}</div><section className="panel"><div className="table-wrap">{children}</div></section></>; }
function Toolbar({ placeholder = 'Search', select = 'All statuses' }: { placeholder?: string; select?: string }) { return <><div className="toolbar-left"><div className="search-box"><Search size={15}/><input className="search" placeholder={placeholder}/></div><select className="select"><option>{select}</option><option>Active</option><option>Pending</option><option>Expired</option></select></div><div className="toolbar-right"><button className="btn"><SlidersHorizontal size={14}/> Filters</button></div></>; }
function UsersPage() { return <Page eyebrow="ADMINISTRATION" title="Users" subtitle="Directory identities and their AccessPilot entitlements."><TablePanel toolbar={<Toolbar placeholder="Search users by name or email" select="All departments"/>}><table><thead><tr><th>User</th><th>Department</th><th>Job title</th><th>Status</th><th>Groups</th><th>Risk / privilege</th><th>Last sign-in</th><th></th></tr></thead><tbody>{users.map(u => <tr key={u.id}><td><Link to={`/admin/users/${u.id}`} className="user-cell"><span className="avatar">{u.initials}</span><span><span className="user-name">{u.name}</span><span className="user-email">{u.email}</span></span></Link></td><td>{u.department}</td><td>{u.title}</td><td><StatusBadge status={u.status}/></td><td>{u.groups}</td><td><span className={`risk ${u.privileged ? 'risk-high' : 'risk-low'}`}>{u.privileged ? 'Privileged' : 'Standard'}</span></td><td>{u.lastSignIn}</td><td><ChevronRight size={15} color="#829198"/></td></tr>)}</tbody></table></TablePanel><p className="footer-note">Showing 5 of 2,486 users · Directory last synced 2 minutes ago</p></Page>; }
function UserDetail() { const { id } = useParams(); const user = users.find(u => u.id === id) || users[0]; return <Page eyebrow="USER DIRECTORY" title={user.name} subtitle={user.email} action={<button className="btn"><Settings2 size={14}/> Manage user</button>}><div className="detail-layout"><section className="panel"><div className="detail-section"><div className="user-cell"><span className="avatar" style={{width:45,height:45}}>{user.initials}</span><div><h2>{user.title}</h2><p className="subtitle">{user.department} · {user.status}</p></div></div></div><div className="detail-section"><div className="detail-title"><h2>Overview</h2><StatusBadge status={user.status}/></div><div className="key-grid"><div className="key"><span>Email</span><strong>{user.email}</strong></div><div className="key"><span>Last sign-in</span><strong>{user.lastSignIn}</strong></div><div className="key"><span>Groups</span><strong>{user.groups} memberships</strong></div><div className="key"><span>Risk posture</span><strong>{user.privileged ? 'Privileged identity' : 'Standard identity'}</strong></div></div></div><div className="detail-section"><div className="detail-title"><h2>Recent activity</h2><Link to="/admin/audit" className="panel-link">View audit</Link></div><div className="timeline"><div className="timeline-item"><strong>Signed in successfully</strong><small>Microsoft Entra ID · Today, 09:42</small></div><div className="timeline-item"><strong>Created access request</strong><small>Production Administrator · Today, 10:14</small></div></div></div></section><aside className="panel"><div className="panel-head"><h2>Access summary</h2></div><div className="detail-section"><div className="key"><span>Active assignments</span><strong>2</strong></div><div className="key" style={{marginTop:20}}><span>Eligible assignments</span><strong>12</strong></div><div className="key" style={{marginTop:20}}><span>Pending requests</span><strong>1</strong></div></div><div className="detail-section"><h2 style={{fontSize:14,marginBottom:14}}>Groups</h2>{groups.slice(0,3).map(g => <div className="activity-row" key={g}><span className="avatar" style={{width:25,height:25,fontSize:9}}><Users size={12}/></span><span className="activity-copy">{g}</span></div>)}</div></aside></div></Page>; }
function Requests({ mine = false }: { mine?: boolean }) { const { requests: items } = useMockState(); const update = (id: string, status: RequestStatus) => { if (status === 'REJECTED' && !window.confirm('Reject this access request?')) return; mockService.transitionRequest(id, status); }; return <Page eyebrow={mine ? 'SELF-SERVICE' : 'ACCESS MANAGEMENT'} title={mine ? 'My requests' : 'Access requests'} subtitle={mine ? 'Track your access requests and approval history.' : 'Review and govern access requests across the environment.'} action={mine ? <Link to="/request-access" className="btn btn-primary"><Plus size={14}/> New request</Link> : undefined}><TablePanel toolbar={<Toolbar placeholder="Search requests"/>}><table><thead><tr><th>Requester</th><th>Resource</th><th>Type</th><th>Provider</th><th>Duration</th><th>Risk</th><th>Status</th><th>Created</th><th>Approval</th><th></th></tr></thead><tbody>{items.filter(r => !mine || r.requester === currentUser.name).map(r => <tr key={r.id}><td className="user-name">{r.requester}</td><td><Link to={`/admin/access-requests/${r.id}`} className="user-name">{r.resource}</Link></td><td>{r.type}</td><td>{r.provider}</td><td>{r.duration}</td><td><span className={`risk risk-${r.risk.toLowerCase()}`}>{r.risk}</span></td><td><StatusBadge status={r.status}/></td><td>{r.created}</td><td>{r.approval}</td><td>{r.status === 'PENDING' ? <span style={{display:'flex',gap:5}}>{mine ? <button className="btn" onClick={() => update(r.id,'CANCELLED')} aria-label="Cancel">Cancel</button> : <><button className="btn" onClick={() => update(r.id,'APPROVED')} aria-label="Approve"><Check size={14}/></button><button className="btn" onClick={() => update(r.id,'REJECTED')} aria-label="Reject"><X size={14}/></button></>}</span> : <ChevronRight size={15} color="#829198"/>}</td></tr>)}</tbody></table></TablePanel></Page>; }
function RequestDetail() { const { id } = useParams(); const req = requests.find(r => r.id === id) || requests[0]; return <Page eyebrow="ACCESS REQUEST" title={req.id} subtitle="Request details and approval history" action={<div style={{display:'flex',gap:8}}><button className="btn btn-primary"><Check size={14}/> Approve</button><button className="btn"><X size={14}/> Reject</button></div>}><div className="detail-layout"><section className="panel"><div className="detail-section"><div className="detail-title"><h2>{req.resource}</h2><StatusBadge status={req.status}/></div><div className="key-grid"><div className="key"><span>Requester</span><strong>{req.requester}</strong></div><div className="key"><span>Provider</span><strong>{req.provider}</strong></div><div className="key"><span>Resource type</span><strong>{req.type}</strong></div><div className="key"><span>Requested duration</span><strong>{req.duration}</strong></div><div className="key"><span>Risk assessment</span><strong className={`risk risk-${req.risk.toLowerCase()}`}>{req.risk} risk</strong></div><div className="key"><span>Ticket number</span><strong>INC-48291</strong></div></div></div><div className="detail-section"><div className="detail-title"><h2>Justification</h2></div><p className="subtitle" style={{lineHeight:1.7,color:'#39525c'}}>{req.justification}</p></div><div className="detail-section"><div className="detail-title"><h2>Policy evaluation</h2><StatusBadge status="SUCCESS"/></div><div className="notice">MFA and a valid ticket are required before activation. The requested duration is within the policy maximum of 4 hours.</div></div></section><aside className="panel"><div className="panel-head"><h2>Request timeline</h2></div><div className="timeline"><div className="timeline-item"><strong>Request created</strong><small>{req.requester} · {req.created}</small></div><div className="timeline-item"><strong>Policy evaluated</strong><small>Passed · Today, 10:14</small></div><div className="timeline-item"><strong>Awaiting approval</strong><small>{req.approval}</small></div></div></aside></div></Page>; }
function RequestDetailInteractive() { const { id } = useParams(); const { requests: items } = useMockState(); const req = items.find(item => item.id === id) || items[0]; const update = (status: RequestStatus) => { if ((status === 'REJECTED' || status === 'CANCELLED') && !window.confirm(`${status === 'REJECTED' ? 'Reject' : 'Cancel'} this access request?`)) return; mockService.transitionRequest(req.id, status); }; return <Page eyebrow="ACCESS REQUEST" title={req.id} subtitle="Request details and approval history" action={<div style={{display:'flex',gap:8}}>{req.status === 'PENDING' && <><button className="btn btn-primary" onClick={() => update('APPROVED')}><Check size={14}/> Approve</button><button className="btn" onClick={() => update('REJECTED')}><X size={14}/> Reject</button></>}</div>}><div className="detail-layout"><section className="panel"><div className="detail-section"><div className="detail-title"><h2>{req.resource}</h2><StatusBadge status={req.status}/></div><div className="key-grid"><div className="key"><span>Requester</span><strong>{req.requester}</strong></div><div className="key"><span>Provider</span><strong>{req.provider}</strong></div><div className="key"><span>Resource type</span><strong>{req.type}</strong></div><div className="key"><span>Requested duration</span><strong>{req.duration}</strong></div><div className="key"><span>Risk assessment</span><strong className={`risk risk-${req.risk.toLowerCase()}`}>{req.risk} risk</strong></div><div className="key"><span>Ticket number</span><strong>INC-48291</strong></div></div></div><div className="detail-section"><div className="detail-title"><h2>Justification</h2></div><p className="subtitle" style={{lineHeight:1.7,color:'#39525c'}}>{req.justification}</p></div><div className="detail-section"><div className="detail-title"><h2>Policy evaluation</h2><StatusBadge status="SUCCESS"/></div><div className="notice">MFA and a valid ticket are required before activation. The requested duration is within the policy maximum of 4 hours.</div></div></section><aside className="panel"><div className="panel-head"><h2>Request timeline</h2></div><div className="timeline"><div className="timeline-item"><strong>Request created</strong><small>{req.requester} · {req.created}</small></div><div className="timeline-item"><strong>Policy evaluated</strong><small>Passed · Today, 10:14</small></div><div className="timeline-item"><strong>{req.status === 'PENDING' ? 'Awaiting approval' : `Request ${req.status.toLowerCase()}`}</strong><small>{req.approval}</small></div></div></aside></div></Page>; }
function MyAccess() { const { assignments: items } = useMockState(); return <Page eyebrow="SELF-SERVICE" title="My access" subtitle="Your active and eligible access across connected providers."><div className="panel" style={{marginBottom:18}}><div className="panel-head"><h2>Eligible access</h2><span className="panel-link">12 available resources</span></div><div className="detail-section"><div className="activity-row"><span className="avatar"><Shield size={14}/></span><div className="activity-copy"><strong>Production Administrator</strong><small>Microsoft Entra ID · Up to 4 hours · Approval required</small></div><Link to="/request-access" className="btn btn-primary">Request <ArrowRight size={13}/></Link></div><div className="activity-row"><span className="avatar"><Users size={14}/></span><div className="activity-copy"><strong>Security Operations</strong><small>Group · Up to 8 hours · MFA required</small></div><Link to="/request-access" className="btn">Request <ArrowRight size={13}/></Link></div></div></div><TablePanel toolbar={undefined}><table><thead><tr><th>Resource</th><th>Type</th><th>Provider</th><th>Status</th><th>Activated</th><th>Expires</th><th>Remaining</th><th></th></tr></thead><tbody>{items.filter(a => a.user === currentUser.name || a.status === 'ACTIVE').slice(0,3).map(a => <tr key={a.id}><td className="user-name">{a.resource}</td><td>{a.type}</td><td>{a.provider}</td><td><StatusBadge status={a.status}/></td><td>{a.start}</td><td>{a.expiration}</td><td>{a.remaining}</td><td><button className="btn">Manage</button></td></tr>)}</tbody></table></TablePanel></Page>; }
function RequestAccess() { const [submitted, setSubmitted] = useState(false); return <Page eyebrow="SELF-SERVICE" title="Request access" subtitle="Request temporary access with a clear business justification."><div className="detail-layout"><section className="panel"><div className="detail-section"><div className="detail-title"><h2>Access details</h2><span className="badge info">Step 1 of 2</span></div><label className="key"><span>Resource</span><select className="select" style={{width:'100%'}}><option>Production Administrator</option><option>Security Administrator</option><option>Product Analytics</option></select></label><div className="key-grid" style={{marginTop:20}}><label className="key"><span>Requested duration</span><select className="select" style={{width:'100%'}}><option>2 hours</option><option>1 hour</option><option>4 hours</option></select></label><label className="key"><span>Ticket number</span><input className="select" placeholder="INC-48291" style={{width:'100%'}}/></label></div><label className="key" style={{display:'block',marginTop:20}}><span>Business justification</span><textarea className="select" rows={5} placeholder="Explain why this access is needed and what you will do."></textarea></label></div><div className="detail-section" style={{display:'flex',justifyContent:'flex-end',gap:8}}><button className="btn">Cancel</button><button className="btn btn-primary" onClick={() => setSubmitted(true)}><SendIcon/> Submit request</button></div></section><aside className="panel"><div className="panel-head"><h2>Policy requirements</h2></div><div className="detail-section">{submitted && <div className="notice" style={{marginBottom:15}}>Request submitted successfully. It is now awaiting approval.</div>}<div className="notice"><strong>Privileged access</strong><br/>This resource requires MFA, an active ticket, and approval from a designated approver. Maximum duration is 4 hours.</div><div className="timeline" style={{padding:'22px 0 0'}}><div className="timeline-item"><strong>Policy evaluation</strong><small>Passed for your identity</small></div><div className="timeline-item"><strong>Approval required</strong><small>Security Operations</small></div><div className="timeline-item"><strong>Activation</strong><small>Available after approval</small></div></div></div></aside></div></Page>; }
function SendIcon() { return <ArrowRight size={14}/>; }
function AssignmentsInteractive() { const { assignments: items } = useMockState(); const update = (assignment: Assignment) => { const next = assignment.status === 'ELIGIBLE' ? 'ACTIVE' : 'REVOKED'; if (next === 'REVOKED' && !window.confirm('Revoke this active assignment?')) return; mockService.transitionAssignment(assignment.id, next); }; return <Page eyebrow="ACCESS MANAGEMENT" title="Assignments" subtitle="Monitor eligible, active, and expired access assignments."><TablePanel toolbar={<Toolbar placeholder="Search assignments"/>}><table><thead><tr><th>User</th><th>Resource</th><th>Type</th><th>Provider</th><th>Status</th><th>Start</th><th>Expiration</th><th>Remaining</th><th></th></tr></thead><tbody>{items.map(a => <tr key={a.id}><td className="user-name">{a.user}</td><td>{a.resource}</td><td>{a.type}</td><td>{a.provider}</td><td><StatusBadge status={a.status}/></td><td>{a.start}</td><td>{a.expiration}</td><td>{a.remaining}</td><td>{a.status === 'ELIGIBLE' || a.status === 'ACTIVE' ? <button className="btn" onClick={() => update(a)}>{a.status === 'ELIGIBLE' ? 'Activate' : 'Revoke'}</button> : <span className="footer-note">No actions</span>}</td></tr>)}</tbody></table></TablePanel></Page>; }
function AssignmentsPage() { return <AssignmentsInteractive />; }
function GroupsPage() { return <Page eyebrow="ADMINISTRATION" title="Groups" subtitle="Directory groups and membership governance." action={<button className="btn btn-primary"><Plus size={14}/> Add group</button>}><TablePanel toolbar={<Toolbar placeholder="Search groups"/>}><table><thead><tr><th>Name</th><th>Description</th><th>Members</th><th>Privileged</th><th>Type</th><th>Status</th><th>Last synced</th><th></th></tr></thead><tbody>{groups.map((g,i) => <tr key={g}><td className="user-name">{g}</td><td>{['Engineering delivery team','Security incident response','Financial reporting access','Product insights workspace','Application administrators'][i]}</td><td>{[42,18,31,64,6][i]}</td><td><span className={`risk ${i === 1 || i === 4 ? 'risk-high':'risk-low'}`}>{i === 1 || i === 4 ? 'Privileged':'Standard'}</span></td><td>Security group</td><td><StatusBadge status="Active"/></td><td>2 min ago</td><td><button className="btn">Manage</button></td></tr>)}</tbody></table></TablePanel></Page>; }
function RolesPage() { return <Page eyebrow="ADMINISTRATION" title="Directory roles" subtitle="Privileged and standard roles available through AccessPilot."><TablePanel toolbar={<Toolbar placeholder="Search roles"/>}><table><thead><tr><th>Role</th><th>Description</th><th>Provider</th><th>Privileged</th><th>Assignment type</th><th>Assigned users</th><th>Status</th></tr></thead><tbody>{roles.map((r,i) => <tr key={r}><td className="user-name">{r}</td><td>{['Full access to all directory resources','Manage security settings and alerts','Elevated production operations','Manage user lifecycle','Read usage and sign-in reports'][i]}</td><td>Microsoft Entra ID</td><td><span className={`risk ${i < 3 ? 'risk-high':'risk-low'}`}>{i < 3 ? 'Yes':'No'}</span></td><td>{i < 3 ? 'Eligible + JIT':'Permanent'}</td><td>{[3,8,5,12,42][i]}</td><td><StatusBadge status="Active"/></td></tr>)}</tbody></table></TablePanel></Page>; }
function PoliciesPage() { return <Page eyebrow="GOVERNANCE" title="Policies" subtitle="Rules that govern access duration, approvals, and assurance." action={<button className="btn btn-primary"><Plus size={14}/> Create policy</button>}><TablePanel toolbar={<Toolbar placeholder="Search policies"/>}><table><thead><tr><th>Policy name</th><th>Description</th><th>Scope</th><th>Max duration</th><th>Approval</th><th>MFA</th><th>Ticket</th><th>Status</th><th></th></tr></thead><tbody>{policies.map(p => <tr key={p.name}><td className="user-name">{p.name}</td><td>{p.description}</td><td>{p.scope}</td><td>{p.max}</td><td>{p.approval}</td><td>{p.mfa}</td><td>{p.ticket}</td><td><StatusBadge status={p.status}/></td><td><button className="btn">Edit</button></td></tr>)}</tbody></table></TablePanel></Page>; }
function AuditPage() { return <Page eyebrow="GOVERNANCE" title="Audit logs" subtitle="A tamper-evident record of identity and access activity."><TablePanel toolbar={<Toolbar placeholder="Search audit events" select="All actions"/>}><table><thead><tr><th>Timestamp</th><th>Actor</th><th>Action</th><th>Target</th><th>Provider</th><th>Result</th><th>Request ID</th></tr></thead><tbody>{auditEvents.map(e => <tr key={e[6]}><td>{e[0]}</td><td className="user-name">{e[1]}</td><td>{e[2]}</td><td>{e[3]}</td><td>{e[4]}</td><td><StatusBadge status={e[5]}/></td><td>{e[6]}</td></tr>)}</tbody></table></TablePanel></Page>; }
function ProvidersPage() { return <ProviderConfiguration />; }
function SyncPage() { return <Page eyebrow="SYSTEM" title="Sync history" subtitle="Provider synchronization runs and reconciliation results."><TablePanel toolbar={<Toolbar placeholder="Search sync runs" select="All providers"/>}><table><thead><tr><th>Run ID</th><th>Provider</th><th>Started</th><th>Completed</th><th>Duration</th><th>Users</th><th>Groups</th><th>Roles</th><th>Errors</th><th>Status</th></tr></thead><tbody>{[['SYNC-08291','Microsoft Entra ID','Today, 09:00','Today, 09:02','02:14','2,486','184','18','0','COMPLETED'],['SYNC-08290','Microsoft Entra ID','Yesterday, 09:00','Yesterday, 09:03','03:02','2,481','184','18','0','COMPLETED'],['SYNC-08289','Microsoft Entra ID','Aug 20, 09:00','Aug 20, 09:04','04:10','2,481','183','18','2','PARTIAL']].map(r => <tr key={r[0]}>{r.map((v,i) => <td key={i} className={i===0 ? 'user-name':''}>{i===9 ? <StatusBadge status={v}/> : v}</td>)}</tr>)}</tbody></table></TablePanel></Page>; }
function Profile() { return <Page eyebrow="SELF-SERVICE" title="Profile" subtitle="Your AccessPilot identity and application role."><div className="detail-layout"><section className="panel"><div className="detail-section"><div className="user-cell"><span className="avatar" style={{width:52,height:52}}>{currentUser.initials}</span><div><h2>{currentUser.name}</h2><p className="subtitle">{currentUser.title}</p></div></div></div><div className="detail-section"><div className="detail-title"><h2>Identity details</h2><StatusBadge status="Active"/></div><div className="key-grid"><div className="key"><span>Email</span><strong>{currentUser.email}</strong></div><div className="key"><span>Department</span><strong>{currentUser.department}</strong></div><div className="key"><span>Identity provider</span><strong>Microsoft Entra ID</strong></div><div className="key"><span>Last sign-in</span><strong>Today, 09:42 UTC</strong></div></div></div></section><aside className="panel"><div className="panel-head"><h2>Application role</h2></div><div className="detail-section"><div className="user-cell"><span className="stat-icon"><ShieldCheck size={16}/></span><div><strong>AccessPilot.Admin</strong><div className="user-email">Development role switcher active</div></div></div><p className="subtitle" style={{lineHeight:1.6,marginTop:18}}>Your role determines which console areas are visible. Authorization is enforced by the backend in production.</p></div></aside></div></Page>; }
export default App;
